Add lock and unlock feature
skodaconnect/myskoda pull request #167
Opened 2024-11-07 08:02 UTC by prvakt

2024-11-07 08:16 UTC, dvx76 commented
Nice work! Can you take a look at `tests/test_operations.py` and see if you can add tests covering the new code there? Should be similar to existing operations.

2024-11-07 09:46 UTC, WebSpider requested changes
Nice work, thanks!

In addition to the adding of tests, please have a look at my small remarks.

2024-11-07 09:46 UTC, WebSpider commented on myskoda/myskoda.py
> +    async def lock(self, vin: str, spin: str) -> None:
Is S-PIN a string? I would expect it to be an integer, but that is based on the input I can give in the app?

2024-11-07 09:46 UTC, WebSpider commented on myskoda/rest_api.py
> +        json_data = {"currentSpin": spin}
Please add typing for the `json_data`

2024-11-07 10:18 UTC, ThraaxSession commented on myskoda/rest_api.py
> +        _LOGGER.debug("Locking vehicle %s", vin)
Prevent logging the VIN, it's a vey personal number and the logging wouldn't help here if there are issues. More importantly is the response, if the VIN or S-Pin is wrong.

2024-11-07 10:19 UTC, ThraaxSession commented on myskoda/rest_api.py
> +        _LOGGER.debug("Unlocking vehicle %s", vin)
Same here.

2024-11-07 10:26 UTC, prvakt commented on myskoda/rest_api.py
> +        _LOGGER.debug("Locking vehicle %s", vin)
I just copied the complete function from another one and changed only name/parameters/endpoint, VIN is traced from every operation currently..

2024-11-07 10:37 UTC, ThraaxSession commented on myskoda/rest_api.py
> +        _LOGGER.debug("Locking vehicle %s", vin)
@WebSpider how do you think about it?

2024-11-07 11:02 UTC, odelma commented on myskoda/myskoda.py
> +    async def lock(self, vin: str, spin: str) -> None:
Can integers have leading zeros? In most cases I dont think so. And S-Pin can be e.g. 0000.

2024-11-07 12:16 UTC, WebSpider commented on myskoda/rest_api.py
> +        _LOGGER.debug("Locking vehicle %s", vin)
No problem with logging level debug. The integration supports multiple vehicles, so this helps in tracing code flow.

Dont log this in info and up.

2024-11-07 14:54 UTC, WebSpider commented
Tests were running for quite some time.

Please test locally by running 'just test' in the project's root (with `Just` installed)

2024-11-07 14:55 UTC, WebSpider commented on myskoda/rest_api.py
> +        json_data = {"currentSpin": spin}
I'm going to remove this remark, since we don't do this for other requests either.
When things quiet down, I'll refactor this all in one go.

2024-11-07 21:27 UTC, dvx76 commented on myskoda/myskoda.py
> +    async def lock(self, vin: str, spin: str) -> None:
Yeah I think we want string here.

2024-11-07 21:29 UTC, dvx76 commented on tests/test_operations.py
> +    topic = f"{USER_ID}/{VIN}/operation-request/vehicle-access/lock-vehicle"
Should be unlock I think?

```suggestion
    topic = f"{USER_ID}/{VIN}/operation-request/vehicle-access/unlock-vehicle"
```

2024-11-07 22:33 UTC, dvx76 approved these changes

2024-11-08 07:50 UTC, WebSpider approved these changes
Thanks for your contribution! 🖖

2024-11-08 07:51 UTC, merged