Add start/stop auxiliary-heating and verify_spin support
skodaconnect/myskoda pull request #175
Opened 2024-11-08 12:26 UTC by prvakt

- Added auxiliary heater support (start/stop). For some reason progress is not published via MQTT so request is just send and not awaited for COMPLETED_SUCCESS status
- Added verify_spin method which returns `CORRECT_SPIN` or `INCORRECT_SPIN` and S-Pin status

2024-11-08 13:02 UTC, dvx76 commented on myskoda/models/spin.py
> +    spinStatus: SpinStatus | None = field(default=None)
Please use `snake_case` for class attributes and and alias in `field_options` to match the field name in the API response. E.g.

```suggestion
@dataclass
class SpinStatus(DataClassORJSONMixin):
    state: str
    remaining_tries: int = field(metadata=field_options(alias="remainingTries"))
    locked_waiting_time_in_seconds: int = field(metadata=field_options(alias="lockedWaitingTimeInSeconds"))

@dataclass
class Spin(DataClassORJSONMixin):
    verification_status: VerificationStatus = field(metadata=field_options(alias="verificationStatus"))
    spin_status: SpinStatus | None = field(default=None, metadata=field_options(alias="verificationSspinStatustatus"))
```

2024-11-08 13:44 UTC, WebSpider requested changes
Thanks for your PR, much appreciated!

Looks good overall, some minor remarks.

2024-11-08 13:44 UTC, WebSpider commented on myskoda/models/spin.py
> +import logging
nit: Models do not need logging

2024-11-08 13:44 UTC, WebSpider commented on myskoda/rest_api.py
> +        """Start the auxiliary heating."""
Will the request actually work with an empty-string S-PIN?
If not, please remove the default.

2024-11-08 13:44 UTC, WebSpider commented on myskoda/rest_api.py
> +                "temperatureValue": str(temperature),
You seem to be forcing `float` conversion to `string` here. Will that work for all accepted inputs?
eg: can we set the temperature to `20.005` ?

2024-11-08 13:44 UTC, WebSpider commented on myskoda/models/spin.py
> +"""Models for responses of api/v2/garage/vehicles/{vin}."""
nit: This should be `/v2/air-conditioning/{vin}/auxiliary-heating/stop`

2024-11-08 15:19 UTC, prvakt commented on myskoda/rest_api.py
> +                "temperatureValue": str(temperature),
implemented rounding to 1 decimal with 0,5 step and updated all methods

2024-11-08 21:15 UTC, dvx76 submitted a review, later dismissed
LGTM

2024-11-08 22:17 UTC, prvakt commented
please wait with approval, planning to test something tomorrow because maybe we are using wrong endpoint for the auxiliary-heating MQTT subscription (https://github.com/skodaconnect/myskoda/issues/179)

2024-11-08 22:48 UTC, WebSpider commented
Converted to draft PR, so it won't be merged by accident.

2024-11-09 08:15 UTC, prvakt commented
Good news, after changing mqtt endpoint for auxiliary-heater as suggested in (https://github.com/skodaconnect/myskoda/issues/179), I can receive state updates. 
This PR is finished and can be merged ;)

2024-11-09 08:44 UTC, WebSpider commented on myskoda/const.py
> +    "departure",
Is this new topic needed for aux heating/verify spin or is it something you discovered along the way?

2024-11-09 08:48 UTC, prvakt commented on myskoda/const.py
> +    "departure",
`departure` and `auxiliary-heating/start-stop-auxiliary-heating` was found by @fursov in #179  so I have added it too

2024-11-09 22:15 UTC, WebSpider commented on myskoda/const.py
> +    "departure",
Good, thanks for your contribution!

2024-11-09 22:15 UTC, WebSpider approved these changes
Lgtm

2024-11-10 15:55 UTC, dvx76 approved these changes

2024-11-10 15:55 UTC, merged