Add fixture Kodiaq from chodorenko
skodaconnect/myskoda pull request #261
Opened 2024-12-03 19:01 UTC by dvx76

From user @chodorenko

2024-12-03 19:18 UTC, WebSpider approved these changes

2024-12-04 08:44 UTC, WebSpider commented
This fixture has capabilities that were recently added, causing tests to fail.

2024-12-08 10:21 UTC, prvakt commented
outside_temperature and FLEET_SUPPORTED are missing, please use fixture from below where its fixed
```
name: Kodiaq
description: Fixtures for Kodiaq Style 2023
generation_time: "2024-12-02T18:40:03.948889+00:00"
library_version: 0.13.4
vehicles:
  - id: 0
    device_platform: MBB_ODP
    system_model_id: NS74QZ
    model: Kodiaq
    model_year: "2023"
    trim_level: Style
    software_version:
    capabilities:
      - id: ACCESS
        statuses: []
      - id: DEALER_APPOINTMENT
        statuses: []
      - id: GEO_FENCE
        statuses: []
      - id: HONK_AND_FLASH
        statuses: []
      - id: MEASUREMENTS
        statuses: []
      - id: NEWS
        statuses:
          - LICENSE_MISSING
      - id: PARKING_POSITION
        statuses: []
      - id: ROADSIDE_ASSISTANT
        statuses: []
      - id: SPEED_ALERT
        statuses: []
      - id: STATE
        statuses: []
      - id: TRIP_STATISTICS
        statuses: []
      - id: VEHICLE_HEALTH_INSPECTION
        statuses: []
      - id: WARNING_LIGHTS
        statuses: []
      - id: VEHICLE_WAKE_UP
        statuses: []
      - id: PAY_TO_FUEL
        statuses: []
      - id: CUBIC
        statuses: []
      - id: SUBSCRIPTIONS
        statuses: []
      - id: DESTINATIONS
        statuses:
          - LICENSE_MISSING
          - LICENSE_EXPIRED
      - id: ICE_VEHICLE_RTS
        statuses: []
      - id: FLEET_SUPPORTED
        statuses: []
      - id: LOYALTY_PROGRAM_WORLDWIDE
        statuses: []
      - id: OUTSIDE_TEMPERATURE
        statuses: []
      - id: DIGICERT
        statuses: []
      - id: VEHICLE_HEALTH_WARNINGS
        statuses: []
      - id: PAY_TO_PARK
        statuses: []
      - id: FUEL_STATUS
        statuses: []
      - id: SERVICE_PARTNER
        statuses: []
      - id: ROUTE_IMPORT
        statuses: []
      - id: MISUSE_PROTECTION
        statuses: []
      - id: CARE_AND_INSURANCE
        statuses: []
reports:
  - type: get
    vehicle_id: 0
    success: true
    endpoint: info
    raw:
      '{"vin": "TMOCKAA0AA000000", "name": "Example Car", "workshopModeEnabled":
      false, "licensePlate": "HH AA 1234", "state": "ACTIVATED", "devicePlatform": "MBB_ODP",
      "specification": {"title": "\u0160koda Kodiaq", "manufacturingDate": "2023-02-12",
      "model": "Kodiaq", "modelYear": "2023", "body": "SUV", "trimLevel": "Style", "systemCode":
      "UNKNOWN", "systemModelId": "NS74QZ", "engine": {"type": "TSI", "powerInKW": 140,
      "capacityInLiters": 2.0}, "gearbox": {"type": "A7A"}}, "servicePartner": {"servicePartnerId":
      "DEU11111"}, "renders": [{"url": "https://iprenders.blob.core.windows.net/basens7v23200004/5X5XDSLGPW-65-Rvio3t1p5gk9_-8s1bgIP.oW_j3BxMlT-qfP3M.TJG0inswacXCg-B0vtg8.XZU6n1mbPqrJdN-OCJWIYSEALQV-19201080dayvext_side1080.png",
      "viewPoint": "exterior_side", "type": "REAL", "order": 0}, {"url": "https://ip-modcwp.azureedge.net/modcwpns7v23200004/5X5XDSLGPW-65-Rvio3t1p5gk9_-8s1bgIP.oW_j3BxMlT-qfP3M.TJG0inswacXCg-B0vtg8.XZU6n1mbPqrJdN-OCJWIYSEALQV-1920658dayvext_side1080.png?v=638329713820000000",
      "viewPoint": "garage_l", "type": "REAL", "order": 1}, {"url": "https://ip-modcwp.azureedge.net/modcwpns7v23200004/5X5XDSLGPW-65-Rvio3t1p5gk9_-8s1bgIP.oW_j3BxMlT-qfP3M.TJG0inswacXCg-B0vtg8.XZU6n1mbPqrJdN-OCJWIYSEALQV-700390dayvext_front1080.png?v=638133583670000000",
      "viewPoint": "main", "type": "REAL", "order": 2}], "compositeRenders": [{"layers":
      [{"url": "https://iprenders.blob.core.windows.net/basens7v23200004/5X5XDSLGPW-65-Rvio3t1p5gk9_-8s1bgIP.oW_j3BxMlT-qfP3M.TJG0inswacXCg-B0vtg8.XZU6n1mbPqrJdN-OCJWIYSEALQV-19201080dayvext_side1080.png",
      "viewPoint": "exterior_side", "type": "REAL", "order": 0}], "viewType": "UNMODIFIED_EXTERIOR_SIDE"},
      {"layers": [{"url": "https://iprenders.blob.core.windows.net/basens7v23200004/5X5XDSLGPW-65-Rvio3t1p5gk9_-8s1bgIP.oW_j3BxMlT-qfP3M.TJG0inswacXCg-B0vtg8.XZU6n1mbPqrJdN-OCJWIYSEALQV-19201080dayvext_side1080.png",
      "viewPoint": "exterior_side", "type": "REAL", "order": 0}], "modifications": {"adjustSpaceInPx":
      {"top": -287, "bottom": -200, "left": -138, "right": -93}, "densityIndependentHeight":
      270, "flipHorizontal": false, "anchorTo": "LEFT"}, "viewType": "HOME"}], "capabilities":
      {"capabilities": [{"id": "ACCESS", "statuses": []}, {"id": "DEALER_APPOINTMENT",
      "statuses": []}, {"id": "GEO_FENCE", "statuses": []}, {"id": "HONK_AND_FLASH",
      "statuses": []}, {"id": "MEASUREMENTS", "statuses": []}, {"id": "NEWS", "statuses":
      ["LICENSE_MISSING"]}, {"id": "PARKING_POSITION", "statuses": []}, {"id": "ROADSIDE_ASSISTANT",
      "statuses": []}, {"id": "SPEED_ALERT", "statuses": []}, {"id": "STATE", "statuses":
      []}, {"id": "TRIP_STATISTICS", "statuses": []}, {"id": "VEHICLE_HEALTH_INSPECTION",
      "statuses": []}, {"id": "WARNING_LIGHTS", "statuses": []}, {"id": "VEHICLE_WAKE_UP",
      "statuses": []}, {"id": "PAY_TO_FUEL", "statuses": []}, {"id": "CUBIC", "statuses":
      []}, {"id": "SUBSCRIPTIONS", "statuses": []}, {"id": "DESTINATIONS", "statuses":
      ["LICENSE_MISSING", "LICENSE_EXPIRED"]}, {"id": "ICE_VEHICLE_RTS", "statuses":
      []}, {"id": "FLEET_SUPPORTED", "statuses": []}, {"id": "LOYALTY_PROGRAM_WORLDWIDE",
      "statuses": []}, {"id": "OUTSIDE_TEMPERATURE", "statuses": []}, {"id": "DIGICERT",
      "statuses": []}, {"id": "VEHICLE_HEALTH_WARNINGS", "statuses": []}, {"id": "PAY_TO_PARK",
      "statuses": []}, {"id": "FUEL_STATUS", "statuses": []}, {"id": "SERVICE_PARTNER",
      "statuses": []}, {"id": "ROUTE_IMPORT", "statuses": []}, {"id": "MISUSE_PROTECTION",
      "statuses": []}, {"id": "CARE_AND_INSURANCE", "statuses": []}]}}'
    url: "/v2/garage/vehicles/TMOCKAA0AA000000?connectivityGenerations=MOD1&connectivityGenerations=MOD2&connectivityGenerations=MOD3&connectivityGenerations=MOD4"
    result:
      state: ACTIVATED
      specification:
        body: SUV
        engine:
          power: 140
          type: TSI
          capacity_in_liters: 2
        model: Kodiaq
        title: Škoda Kodiaq
        manufacturing_date: "2023-02-12"
        model_year: "2023"
        system_code: UNKNOWN
        system_model_id: NS74QZ
        battery:
        max_charging_power:
        trim_level: Style
      vin: TMOCKAA0AA000000
      name: Example Car
      capabilities:
        capabilities:
          - id: ACCESS
            statuses: []
          - id: DEALER_APPOINTMENT
            statuses: []
          - id: GEO_FENCE
            statuses: []
          - id: HONK_AND_FLASH
            statuses: []
          - id: MEASUREMENTS
            statuses: []
          - id: NEWS
            statuses:
              - LICENSE_MISSING
          - id: PARKING_POSITION
            statuses: []
          - id: ROADSIDE_ASSISTANT
            statuses: []
          - id: SPEED_ALERT
            statuses: []
          - id: STATE
            statuses: []
          - id: TRIP_STATISTICS
            statuses: []
          - id: VEHICLE_HEALTH_INSPECTION
            statuses: []
          - id: WARNING_LIGHTS
            statuses: []
          - id: VEHICLE_WAKE_UP
            statuses: []
          - id: PAY_TO_FUEL
            statuses: []
          - id: CUBIC
            statuses: []
          - id: SUBSCRIPTIONS
            statuses: []
          - id: DESTINATIONS
            statuses:
              - LICENSE_MISSING
              - LICENSE_EXPIRED
          - id: ICE_VEHICLE_RTS
            statuses: []
          - id: FLEET_SUPPORTED
            statuses: []
          - id: LOYALTY_PROGRAM_WORLDWIDE
            statuses: []
          - id: OUTSIDE_TEMPERATURE
            statuses: []
          - id: DIGICERT
            statuses: []
          - id: VEHICLE_HEALTH_WARNINGS
            statuses: []
          - id: PAY_TO_PARK
            statuses: []
          - id: FUEL_STATUS
            statuses: []
          - id: SERVICE_PARTNER
            statuses: []
          - id: ROUTE_IMPORT
            statuses: []
          - [...]

2024-12-10 16:39 UTC, prvakt requested changes
finally figured it out how to suggest changes heh.. fixture should pass all tests once my changes are applied ;)

2024-12-10 16:39 UTC, prvakt commented on fixtures/Fixtures_for_Kodiaq_Style_2023.yaml
> +      - id: OUTSIDE_TEMPERATURE
```suggestion
      - id: FLEET_SUPPORTED
        statuses: []
      - id: OUTSIDE_TEMPERATURE
```

2024-12-10 16:39 UTC, prvakt commented on fixtures/Fixtures_for_Kodiaq_Style_2023.yaml
> +          - id: LOYALTY_PROGRAM_WORLDWIDE
```suggestion
          - id: FLEET_SUPPORTED
            statuses: []
          - id: LOYALTY_PROGRAM_WORLDWIDE
```

2024-12-10 16:39 UTC, prvakt commented on fixtures/Fixtures_for_Kodiaq_Style_2023.yaml
> +    error:
```suggestion
          outside_temperature:
    error:
```

2024-12-10 16:44 UTC, prvakt requested changes

2024-12-10 16:44 UTC, prvakt commented on fixtures/Fixtures_for_Kodiaq_Style_2023.yaml
> +---
don't know if this is allowed or not, other fixutures doesn't have ```---``` on first line
```suggestion
```

2024-12-11 17:58 UTC, prvakt approved these changes

2024-12-11 18:24 UTC, dvx76 commented
Thanks for the help @prvakt !

2024-12-11 18:25 UTC, merged