Add exception for redirect to marketing consent
skodaconnect/myskoda pull request #284
Opened 2024-12-15 07:20 UTC by Thor77

during login the process can halt because the user is redirected to a marketing constent page. Without catching this condition a KeyError Location is raised because it's the final page but doesn't start with `myskoda://`.

Ref #277

2024-12-15 12:44 UTC, WebSpider requested changes

2024-12-15 12:44 UTC, WebSpider commented on myskoda/auth/authorization.py
> +                    if "consent/marketing" in location:
Please rename exception to MarketingConsentError, it contains a typo now

2024-12-16 08:33 UTC, Thor77 commented on myskoda/auth/authorization.py
> +                    if "consent/marketing" in location:
argh, sry, fixed

2024-12-16 09:06 UTC, WebSpider approved these changes
lgtm

2024-12-16 09:07 UTC, merged