Add calculated state of the doors and windows
skodaconnect/myskoda pull request #42
Opened 2024-09-26 17:45 UTC by fursov

Calculated from renders that response messsage contains. Probably not very reliable method. Error cases assumed, return closed state if parsing fails for any reason.

Added tests for different states.

2024-09-26 17:46 UTC, fursov commented
I also would like to understand if this feature is ok to have. Please, provide your feedback.

2024-09-27 06:42 UTC, Prior99 requested changes
Awesome work. I was also planning to do this, but I never found the time.

Please take a look at the comments I've left you :)

2024-09-27 06:42 UTC, Prior99 commented on myskoda/models/status.py
> +class CarBodyElements(IntEnum):
We're naming enum members in `UPPER_SNAKE_CASE`.

2024-09-27 06:42 UTC, Prior99 commented on myskoda/models/status.py
> +    class _CarWindowDoorStates(IntEnum):
Please, no classes inside of classes :)

2024-09-27 06:42 UTC, Prior99 commented on myskoda/models/status.py
> +            _LOGGER.debug("Unable to parse vehicle status query for doors/windows state")
This should log an error.

2024-09-27 06:42 UTC, Prior99 commented on myskoda/models/status.py
> +    def _get_vehicle_state(self) -> list[int]:
I think the method name is misleading.
This method takes the URL's and parses it into a list of integers.

`_extract_window_door_int_from_url`

Or something similar would be more fitting.

2024-09-27 06:42 UTC, Prior99 commented on myskoda/models/status.py
> +            return [1, 1, 1, 1, 0, 0, 0, 0, 0]
Instead of having multiple `try ... except` blocks which ultimately all lead to the method just returning `[1, 1, 1, 1, 0, 0, 0, 0, 0]`, you could just have one `try ... except` block around the whole body of the method and then return this here.
 
Will be less code and less computation.

2024-09-27 06:42 UTC, Prior99 commented on myskoda/models/status.py
> +    DOOR_OPENED = "Door opened"
Please rename to `DOOR_OPEN` and `WINDOW_OPEN`.

2024-09-27 06:42 UTC, Prior99 commented on tests/test_status.py
> +FULL_CONFIG = {
Please move this into a fixture file.

2024-09-27 17:25 UTC, fursov commented on myskoda/models/status.py
> +class CarBodyElements(IntEnum):
Done

2024-09-27 17:25 UTC, fursov commented on myskoda/models/status.py
> +    DOOR_OPENED = "Door opened"
Done

2024-09-27 17:25 UTC, fursov commented on myskoda/models/status.py
> +    class _CarWindowDoorStates(IntEnum):
Done

2024-09-27 17:26 UTC, fursov commented on myskoda/models/status.py
> +            _LOGGER.debug("Unable to parse vehicle status query for doors/windows state")
Done

2024-09-27 17:26 UTC, fursov commented on myskoda/models/status.py
> +            return [1, 1, 1, 1, 0, 0, 0, 0, 0]
Done, return shorted list for doors/windows only, other elements states can be fetched from other Status fields

2024-09-27 17:26 UTC, fursov commented on tests/test_status.py
> +FULL_CONFIG = {
Done

2024-09-28 08:54 UTC, dvx76 approved these changes

2024-09-28 08:54 UTC, dvx76 commented on tests/test_status.py
> +def test_door_window_states_all_closed_parsed_ok(vehicle_status: dict) -> None:
No need to update the PR for this, just FYI, take a look at pytest parametrize (https://docs.pytest.org/en/stable/how-to/parametrize.html#parametrize-basics). It's awesome for tests like this where you're testing a various function inputs against expected output but structure of the test itself is identical between each test.

And thanks for including tests !

2024-09-29 10:17 UTC, Prior99 approved these changes

2024-09-29 10:17 UTC, merged