Error handling for trip-statistics in CLI
skodaconnect/myskoda pull request #68
Opened 2024-09-30 07:46 UTC by OBerghmans

I tried to add a minimal solution to better handle the trip-statistics error:
  - Added an exception in the rest_api module. The _make_get_request still throws an exception, so behaviour in the overall library should remain the same
  - The CLI catches the new exception and prints it

This should fix #58 , at least by printing the error result instead of throwing an exception.

It also takes into account @dvx76 's remark  that 

> The integration will use get_vehicle which will only try to get statistics if the TRIP_STATISTICS capability is present.

The CLI also still exposes all methods but does not error in case there are no trip statistics.

The fix is minimal in the sense that I think it would be overkill for the trip-statistics method to first check the capabilities and then - depending on the capability being present - get the trip statistics. But that's also a way we could go.

2024-09-30 07:59 UTC, Prior99 requested changes

2024-09-30 07:59 UTC, Prior99 commented on myskoda/cli.py
> +        ctx.obj["print"]({"error": e.response})
I like this, but can't this happen in every route? Not only just trip statistics. I think we can even add this in a generic way, and add this to the `_make_get_request`.

2024-09-30 08:00 UTC, Prior99 commented on myskoda/cli.py
> +        ctx.obj["print"]({"error": e.response})
Perhaps it would be even better to simply check the HTTP status code. Perhaps the response body will always be a string if it's not a 200 code?

2024-09-30 09:42 UTC, OBerghmans commented on myskoda/cli.py
> +        ctx.obj["print"]({"error": e.response})
Checking the status code might be a good idea. I'll check what it is for the failed trip-statistics call.

For your first comment: a generic way can be checked. I think it would be mainly in the CLI class then. I'm not sure if we could add the generic way in the RestApi class, as we probably don't always want to just print that failure/response message. In a way I already did it generic: the entity using the _make_get_request (in this case the CLI) can decide what to do with the error. Perhaps sometimes we just want to catch it and not report on it.

2024-09-30 10:14 UTC, OBerghmans commented on myskoda/cli.py
> +        ctx.obj["print"]({"error": e.response})
The status code was 404. I now use the raise_for_status built-in functionality for raising an exception if the result was not 200. The removes the need for a new exception (although I don't have the plain text response now). So let me know if we would rather have that one as well.

2024-09-30 10:34 UTC, OBerghmans commented on myskoda/cli.py
> +        ctx.obj["print"]({"error": e.response})
I just pushed a more generic way in the CLI method. Closing this conversation on the outdated file. Looking forward to feedback though!

2024-10-01 08:06 UTC, WebSpider reviewed
Small question, otherwise lgtm

2024-10-01 08:06 UTC, WebSpider commented on myskoda/rest_api.py
> +            response.raise_for_status()
If we raise here, where do we catch the exception?

2024-10-01 08:14 UTC, OBerghmans commented on myskoda/rest_api.py
> +            response.raise_for_status()
This will throw an exception (obviously) but in this situation the deserialize would have also threw an exception. So same result, just another exception class. I searched the code and everywhere else it was catched by 'except Exception' so this would still be the case. 

And in the CLI class I specifically catch this one to print a nicer output instead of exiting the app with a stack trace

2024-10-01 08:37 UTC, OBerghmans commented on myskoda/rest_api.py
> +            response.raise_for_status()
Also, the integration does extra checks (checking if the trip statistics capability is present before calling that endpoint) so that decreases the chances of getting the exception. There will probably be extra places where we can intercept this exception and improve. So in that point of view this is the start of some extra error handling when the API returns an error/Plain text/...

2024-10-01 10:21 UTC, WebSpider approved these changes
lgtm

2024-10-07 06:32 UTC, merged