Fix driving range parsing for hybrid cars
skodaconnect/myskoda pull request #70
Opened 2024-09-30 18:00 UTC by fursov

Test added.

To fix #69

2024-10-01 06:35 UTC, WebSpider approved these changes
Smalle request to split tests for engine types. Behaviour may be different.

2024-10-01 06:37 UTC, WebSpider requested changes

2024-10-01 06:37 UTC, WebSpider commented on tests/test_driving_range.py
> +async def test_get_driving_range() -> None:
Can you make this a seperate test for a hybrid engine and a 'mono' engine?

2024-10-01 06:50 UTC, fursov commented on tests/test_driving_range.py
> +async def test_get_driving_range() -> None:
Would be great if you (or someone else) could send me example of example of the response for mono engine, I will make it part of the test.

2024-10-01 07:57 UTC, WebSpider commented on tests/test_driving_range.py
> +async def test_get_driving_range() -> None:
For an electric engine:

```json
{"carType":"electric","totalRangeInKm":139,"primaryEngineRange":{"engineType":"electric","currentSoCInPercent":41,"remainingRangeInKm":139},"carCapturedTimestamp":"2024-10-01T06:54:54Z"}
```

I dont have a mono ICU to contribute at the moment.

2024-10-02 15:28 UTC, fursov commented on tests/test_driving_range.py
> +async def test_get_driving_range() -> None:
Which car model is this? We are currently collecting fixtures per car model like enyaq or superb...

2024-10-03 09:42 UTC, WebSpider approved these changes

2024-10-03 09:43 UTC, merged