Remove async-with
skodaconnect/myskoda pull request #71
Opened 2024-10-01 09:42 UTC by WebSpider

- Introduce internal methods for different requests
- Add universal timeout handling

Fixes #46 

TODO: Needs testing

2024-10-10 14:54 UTC, Prior99 requested changes

2024-10-11 09:08 UTC, Prior99 commented
I took the liberty to rebase this

2024-10-11 10:28 UTC, Prior99 approved these changes

2024-10-11 10:29 UTC, merged

2024-10-11 18:49 UTC, WebSpider commented
Why was this merged?
It was a draft PR?

2024-10-11 19:03 UTC, dvx76 commented
Got it. `await response.text()` is called after the `self.session.request` context manager has closed. One line fix.