Add deserialization for time_to_finish
skodaconnect/myskoda pull request #88
Opened 2024-10-09 09:50 UTC by WebSpider

Apparently, timeToFinish can be "null" according to issue skodaconnect/homeassistant-myskoda/issues/78

This adds a deserializer to handle the case

2024-10-10 17:00 UTC, dvx76 submitted a review, later dismissed

2024-10-11 08:29 UTC, Prior99 requested changes

2024-10-11 08:29 UTC, Prior99 commented on myskoda/models/service_event.py
> +        return 0
Are you sure this is semantically a `0` and not rather `None`?

2024-10-11 08:47 UTC, WebSpider commented on myskoda/models/service_event.py
> +        return 0
The case here is that the car is currently not charging, so I guess a None would be more correct.
We would need to handle the case in the integration to determine what the None should correspond to.

I guess a sane state there would be "Unavailable"

2024-10-11 20:14 UTC, Prior99 commented on myskoda/models/service_event.py
> +        return 0
`None` corresponds to HA's unavailable.

2024-10-13 19:22 UTC, dvx76 approved these changes

2024-10-14 15:15 UTC, merged